// Command gendevices plans the simulated installation and writes the compose
// services for it. Each device is its own container: in the simulation the
// container is the physical device, and starting it is mounting it on the
// wall. Registering it with the installer's tool is a separate step.
//
//	go run ./cmd/gendevices -plan 50   # pick rooms, write deploy/devices.csv
//	go run ./cmd/gendevices            # write compose.devices.yaml from it
package main

import (
	"encoding/csv"
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"math/rand/v2"
	"os"
	"sort"
	"strings"
)

// Kinds installed in every room, and the id prefix of each (the label a
// manufacturer would print).
var perRoom = []struct{ kind, prefix string }{
	{"co2", "co2"}, {"temp", "temp"}, {"occupancy", "occ"},
	{"damper", "damper"}, {"heating", "heat"},
}

func main() {
	plan := flag.Int("plan", 0, "pick this many rooms and write the installation list")
	fika := flag.String("fika", "1570,A1023,A117", "occupancysim's fika rooms on the level (always included)")
	lectures := flag.Int("lectures", 20, "lecture rooms to include when planning")
	level := flag.String("level", "level0", "level to plan")
	floorplan := flag.String("floorplan", "external/buildingsim/data/abuilding/level0/floorplan_data.json", "floor plan of the level")
	seed := flag.Uint64("seed", 1, "seed for the room choice")
	list := flag.String("csv", "deploy/devices.csv", "installation list")
	out := flag.String("out", "compose.devices.yaml", "generated compose file")
	flag.Parse()

	if *plan > 0 {
		keys, err := pickRooms(*floorplan, *level, strings.Split(*fika, ","), *lectures, *plan, *seed)
		if err != nil {
			log.Fatal(err)
		}
		if err := writeList(*list, keys); err != nil {
			log.Fatal(err)
		}
		fmt.Printf("wrote %s: %d rooms, %d devices\n", *list, len(keys), len(keys)*len(perRoom))
	}
	devices, err := readList(*list)
	if err != nil {
		log.Fatal(err)
	}
	if err := writeCompose(*out, devices); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote %s: %d device containers\n", *out, len(devices))
}

// pickRooms takes the fika rooms, then lecture rooms (≥ 60 m²), then offices
// (6–40 m²) at random with a fixed seed, so the room set is reproducible.
func pickRooms(path, level string, fika []string, lectures, total int, seed uint64) ([]string, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var fp struct {
		Rooms []struct {
			Name string  `json:"name"`
			Area float64 `json:"area"`
			Type string  `json:"type"`
		} `json:"rooms"`
	}
	if err := json.Unmarshal(b, &fp); err != nil {
		return nil, err
	}
	isFika := map[string]bool{}
	for _, f := range fika {
		isFika[f] = true
	}
	var lecture, office []string
	for _, r := range fp.Rooms {
		m2 := r.Area * 0.25
		switch {
		case r.Type != "room" || isFika[r.Name]:
		case m2 >= 60:
			lecture = append(lecture, r.Name)
		case m2 >= 6 && m2 <= 40:
			office = append(office, r.Name)
		}
	}
	rng := rand.New(rand.NewPCG(seed, 0))
	rng.Shuffle(len(lecture), func(i, j int) { lecture[i], lecture[j] = lecture[j], lecture[i] })
	rng.Shuffle(len(office), func(i, j int) { office[i], office[j] = office[j], office[i] })

	names := append([]string{}, fika...)
	names = append(names, lecture[:min(lectures, len(lecture))]...)
	if rest := total - len(names); rest > 0 {
		names = append(names, office[:min(rest, len(office))]...)
	}
	names = names[:min(total, len(names))]
	sort.Strings(names)
	keys := make([]string, len(names))
	for i, n := range names {
		keys[i] = level + "/" + n
	}
	return keys, nil
}

func writeList(path string, keys []string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	w := csv.NewWriter(f)
	w.Write([]string{"id", "kind", "room"})
	for i, k := range keys {
		for _, d := range perRoom {
			w.Write([]string{fmt.Sprintf("%s-%04d", d.prefix, i+1), d.kind, k})
		}
	}
	w.Flush()
	return w.Error()
}

type device struct{ id, kind, room string }

func readList(path string) ([]device, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	records, err := csv.NewReader(f).ReadAll()
	if err != nil {
		return nil, err
	}
	var out []device
	for i, r := range records {
		if i == 0 {
			continue
		}
		out = append(out, device{r[0], r[1], r[2]})
	}
	return out, nil
}

func writeCompose(path string, devices []device) error {
	var b strings.Builder
	b.WriteString(`# Generated by cmd/gendevices from deploy/devices.csv. Do not edit by hand.
# One container per device: in the simulation, the container is the device.
# Inject a fault into one device with FAULT_<ID>, e.g.
#   FAULT_CO2_0001=stuck docker compose up -d co2-0001

x-sensor: &sensor
  image: d7065e/sensor
  pull_policy: never
  restart: unless-stopped
x-actuator: &actuator
  image: d7065e/actuator
  pull_policy: never
  restart: unless-stopped
x-device-env: &device-env
  RUN_ID: ${RUN_ID:-dev}
  REGISTRY_URL: http://registry:8080
  BUILDSIM_URL: http://buildsim:9090
  PHYSICS_URL: http://physics:8080
  CLOCK_URL: http://occupancysim:8081
  MQTT_URL: tcp://mosquitto:1883

services:
`)
	seen := map[string]bool{}
	var roomsList []string
	for _, d := range devices {
		if !seen[d.room] {
			seen[d.room] = true
			roomsList = append(roomsList, d.room)
		}
	}
	fmt.Fprintf(&b, "  physics:\n    environment:\n      ROOMS: %q\n\n", strings.Join(roomsList, ","))

	for _, d := range devices {
		anchor, user := "sensor", "sensor"
		if d.kind == "damper" || d.kind == "heating" {
			anchor, user = "actuator", "actuator"
		}
		envName := "FAULT_" + strings.ToUpper(strings.ReplaceAll(d.id, "-", "_"))
		fmt.Fprintf(&b, "  %s:  # %s in %s\n    <<: *%s\n    environment:\n      <<: *device-env\n", d.id, d.kind, d.room, anchor)
		fmt.Fprintf(&b, "      DEVICE_ID: %s\n      DEVICE_KIND: %s\n      MQTT_USER: %s\n      MQTT_PASS: %s-pw\n", d.id, d.kind, user, user)
		if anchor == "sensor" {
			fmt.Fprintf(&b, "      FAULT: ${%s:-}\n", envName)
		} else {
			// The service name is the device's address on the compose network;
			// the container's own hostname isn't resolvable by the others.
			fmt.Fprintf(&b, "      ADVERTISE_URL: http://%s:8080\n", d.id)
		}
		b.WriteString("\n")
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
